### ISSUE TITLE
Possible to add a name or a date in the filename in case we move the file around

### ISSUE THREAD

**Issue by Toasterme** [ikifar2012/remote-backup-addon#13]
hi ! addon seem to work, followed the direction from this blog : https://maartendamen.com/how-do-i-back-up-home-assistant/

I have 2 questions : 
1) why do i have 2 files ?
2) is it possible to customize the filename instead of random number + adding a custom date format at the end of the file

**Comment by ikifar2012** [comment]
Thank you for using my addon

I didn't even know someone made a blog post about my addon, cool

On to your questions 

1. I'd like more information on this, I am unsure what you mean by 2 files I only get one
2. As it stands right now the addon just SCP's whatever is in the backup folder, Home Assistant generates the name as a slug which is that random string of characters you are seeing, I will look into possibly adding code to the script to rename the file.

In terms of a custom date format what do you think that would look like? Right now I was thinking of modifying the tar to be the same as the snapshot name in the UI.

**Comment by ikifar2012** [comment]
Let me know what you think of the changes

**Comment by Toasterme** [comment]
Thanks a lot ! date suffix is good for me, i always put yyyy-mm-dd in that order, so that's perfect for me!

Wanted to test it yesterday but the plugin was not updated and could not find how to force the update (still don't).  Pluging seem to be updated and works as you said.  

About the 2 files, i don't know, i lost the log, and i have only one now, must be something i did to get two files, 5min apart.

Thanks again for making it easier to backup our Home Assistant !

**Comment by ikifar2012** [comment]
To force your Home Assistant Addon Store to check for updates:
Go to Supervisor > Addon Store > Click the 3 dots at the top right > Click Reload
![image](https://user-images.githubusercontent.com/20800434/113630650-35cd9d00-9636-11eb-8fc1-339f5902125f.png)

Thanks again for using my addon, is it safe to say the issue can now be marked as closed?

**Comment by Toasterme** [comment]
Oh thanks for this tricks !  yes we can close this, thanks again for your help !
