### ISSUE TITLE
rsync portion of remote backup is failing

### ISSUE THREAD

**Issue by neillbell** [ikifar2012/remote-backup-addon#134]
Core 2024.3.3
Supervisor 2024.03.0
Operating System 12.1 

I have been using this addon for a while and the rsync function used to work well. I just noticed that the rsync target directory did not have much in it and so I investigated. The logs show the following:

```
[22:05:03] INFO: Copying backup using rsync.
rsync: [sender] link_stat "/all_addon_configs" failed: No such file or directory (2)
rsync: [sender] link_stat "/homeassistant_config" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1336) [sender=3.2.7]
[22:05:07] ERROR: Error rsyncing folder(s) /addons /all_addon_configs /backup /config /homeassistant_config /media /share /ssl to root@host.example.org:/storage/homeassistant/hassio-sync: unknown error: 23!
```
My configuration contains:
```
remote_host: host.example.org
remote_port: 22
remote_user: root
remote_key: id_rsa
backup_friendly_name: true
backup_custom_prefix: ha-backup-
backup_keep_local: "1"
ssh_enabled: true
ssh_remote_directory: /storage/homeassistant
rsync_enabled: true
rsync_rootfolder: /storage/homeassistant/hassio-sync
rsync_exclude: []
```
Is something misconfigured?

**Comment by ikifar2012** [comment]
Thanks for bringing this to my attention, after running a backup on my own instance I too am experiencing the issue. I will look into this sometime within the next couple of days I believe something has changed within HA

**Comment by ikifar2012** [comment]
Sorry for the delay... the latest release should solve the issue, thanks again for reporting, please let me know if it works

**Comment by neillbell** [comment]
Everything looks great. Thanks for the fix!
