### ISSUE TITLE
Add-on only runs after initial config save or HA add-on restart

### ISSUE THREAD

**Issue by derekcentrico** [ikifar2012/remote-backup-addon#150]
Setup:  I'm running add-on version "2024.6.0".  I installed it with HA version 2024.6.1 and currently am running HA 2024.6.3.  HA runs standalone on the Green.

Issue:  The add-on will run just one time, either upon save of a new configuration -or- upon starting the add-on again from the INFO page.  Nothing is automated like via cron or anything.  

Add-on config:
```
remote_host: 192.168.1.4
remote_port: 22
remote_user: haosbackup
remote_key: ""
backup_friendly_name: true
backup_custom_prefix: Automated backup
backup_keep_local: "1"
ssh_enabled: true
ssh_remote_directory: automated_backups
rsync_enabled: false
rsync_rootfolder: hassio-sync
rsync_exclude:
  - /config/*.db-shm
  - /config/*.db-wal
  - /config/*.db
remote_password: admin
```
Log:

> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service base-addon-banner: starting
> 
> -----------------------------------------------------------
>  Add-on: Remote Backup
>  Automatically create and transfer HA backups using SFTP (SCP), rsync, or rclone (experimental)
> -----------------------------------------------------------
>  Add-on version: 2024.6.0
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 12.4  (aarch64 / green)
>  Home Assistant Core: 2024.6.3
>  Home Assistant Supervisor: 2024.06.0
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> s6-rc: info: service base-addon-banner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service base-addon-log-level: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service base-addon-log-level successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> s6-rc: info: service legacy-services successfully started
> [11:33:18] WARNING: 
> [11:33:18] WARNING: Setting a password is highly recommended!
> [11:33:18] WARNING: 
> [11:33:18] WARNING: Please set a password in the 'backup_password' option.
> [11:33:18] WARNING: 
> [11:33:18] WARNING: If unsure, check the add-on manual for more information.
> [11:33:18] WARNING: 
> [11:33:18] NOTICE: Migration complete.
> [11:33:18] NOTICE: Creating directories for failed backup alerts.
> [11:33:19] NOTICE: Directories created.
> [11:33:19] NOTICE: Setup complete.
> [11:33:19] INFO: Adding SSH configuration.
> [11:33:19] INFO: Creating non-encrypted full backup: "Automated backup 2024-06-20 11-33"
> [11:41:27] INFO: Backup created: 7d9d0c4f
> [11:41:27] INFO: Copying backup using SFTP/SCP.
> 
> [11:43:54] NOTICE: Deleting local backup: 4d01e561
> 
> [11:43:55] NOTICE: Deleting local backup: d1353967
> 
> [11:43:55] NOTICE: Deleting local backup: a722096f
> 
> [11:43:55] NOTICE: Deleting local backup: a759a9ca
> 
> [11:43:55] NOTICE: Deleting local backup: ebd33616
> 
> [11:43:56] NOTICE: Deleting local backup: 69bda9b2
> 
> [11:43:56] NOTICE: Deleting local backup: f30fb057
> 
> [11:43:56] NOTICE: Deleting local backup: b55b6c9c
> 
> [11:43:56] NOTICE: Deleting local backup: 3ba37aee
> 
> [11:43:56] INFO: Backup process done!
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service base-addon-log-level: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service base-addon-log-level successfully stopped
> s6-rc: info: service base-addon-banner: stopping
> s6-rc: info: service base-addon-banner successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

Screenshot of the add-on page showing it "red":

![image](https://github.com/ikifar2012/remote-backup-addon/assets/1930094/ba7041c2-fc38-455c-89c9-87bd1510e003)

The last backup created was on "2024-06-20 11-33".

Not sure what I'm missing here?

**Comment by derekcentrico** [comment]
Or, does this actually require an automation?  I was working on the assumption an automation allows further backup refinement.

**Comment by ikifar2012** [comment]
> Or, does this actually require an automation? I was working on the assumption an automation allows further backup refinement.

Sorry the issue closed on you and I didn't see it, basically the way it works is when the addon is started it kicks off the script then the container stops when the script exits so yes you do need an automation 

Check this out for an example automation 
https://addons.mathesonsteplock.ca/docs/addons/remote-backup/blueprints-automations
