### ISSUE TITLE
[FR] Add boolean available for HA automations 

### ISSUE THREAD

**Issue by SirGoodenough** [ikifar2012/remote-backup-addon#36]
A 'Nice to Have' would be some exported boolean that HA can used to tell me if the last back-up was successful.
I recently had a 12 day stretch where the back-up had a problem and I did not know it.

As another thought, possibly a sensor that lists the time/date the last successful backup occurred could also be useful.

Sometimes the old Linux machine I have my drive spinning on locks up, and I will get the snapshot but it will not send it off the main instance, and I would like to capture / remedy that when it happens.

**Comment by talljohnson** [comment]
Further use-case for additional consideration.

I have an automation that performs a weekly backup. In my automation, after the call to backup, I have a message sent to me. I have noticed that the message is sent immediately after the call to start the backup Add-on. This indicates to me that the home assistant add-on call is asynchronous. So, my current automation with my message does not provide insight that the backup completed. My message indicates that the backup call was started.

Example:
Trigger: 3AM
Condition: Monday
Action:
     Service call: hassio.addon_start --> Remote Backup slug
     Service call: telegram_bot.send_message --> "Weekly backup complete"

I get a message immediately at 3AM. The file backup doesn't complete for 10 minutes. It would be nice to have a trigger event from the backup addon knowing if the backup was successful at ~3:10AM, indicating success of failure.
