### ISSUE TITLE
Issue with spaces in remote path

### ISSUE THREAD

**Issue by uberboffin** [ikifar2012/remote-backup-addon#43]
Version info:

```
 Add-on version: 2022.5.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.6  (amd64 / qemux86-64)
 Home Assistant Core: 2022.4.5
 Home Assistant Supervisor: 2022.05.2
```

We are using SCP to copy to a remote Mac server. The path needs to be escaped, as it has spaces in it. The add-on does use quotes for the path, so I can simply enter the path into the config file. However, if I do not escape, then the following error is shown:

```
scp: ambiguous target
```

If I do escape the string, then the move of the tar to the friendly name then breaks, as you cannot mix quotes and escaped spaces together.

**Comment by patman15** [comment]
fixed in commit https://github.com/ikifar2012/remote-backup-addon/pull/59/commits/a31d17f6fcc4469483cc3c1e064ed42ad11f94b8 PR https://github.com/ikifar2012/remote-backup-addon/pull/59
