### ISSUE TITLE
Remote backup always does a full backup

### ISSUE THREAD

**Issue by MarekLe** [ikifar2012/remote-backup-addon#45]
Version info:
```
- plugin: 2022.5.1
- Home Assistant 2022.7.2
- Supervisor 2022.07.0
- Operating System 8.2
- Frontend 20220707.0 - latest
```

Plugin ignoring config parameters:
- exclude_folders
- exclude_addons

The effect is that the backup does not fit on the disk. I don't want to back up the 'media' directory!
The problem seems to me after the last Home Assistant update.
Unfortunately, the plugin is useless at the moment.

**Comment by ikifar2012** [comment]
Can you share your config with me?

**Comment by MarekLe** [comment]
`debug: true
ssh_enabled: true
friendly_name: true
custom_prefix: Automated backup
ssh_host: 192.168.1.144
ssh_port: 22
ssh_user: root
ssh_key: HA_id_rsa
ssh_host_key_algorithms: ''
exclude_folders: media
exclude_addons: >-
  a0d7b954_influxdb, core_mariadb, ccab4aaf_frigate, a0d7b954_unifi,
  a0d7b954_vscode, 86689438_joplin
remote_directory: /srv/dev-disk-by-uuid-cf377038-b875-43cb-a3c8-afcc4025afb5/HA_Backups
zip_password: ''
keep_local_backup: '1'
rsync_enabled: false
rsync_verbose: false
rsync_host: ''
rsync_rootfolder: hassio-sync
rsync_exclude: ''
rsync_user: ''
rsync_password: ''
rclone_enabled: false
rclone_copy: false
rclone_sync: false
rclone_restore: false
rclone_remote: ''
rclone_remote_directory: ''
`

**Comment by ikifar2012** [comment]
Please update to 2022.7.0 and let me know if your problem is solved, if your problem is not solved feel free to re-open this issue

**Comment by MarekLe** [comment]
It's working good. Thank you.

śr., 20 lip 2022, 06:15 użytkownik Matheson Steplock <
***@***.***> napisał:
