### ISSUE TITLE
no backup file created

### ISSUE THREAD

**Issue by terri1769** [ikifar2012/remote-backup-addon#55]
I finally got SSH working properly from the HA server to my NAS.  That was a permissions issue on .ssh and .authorized_keys on the server.  Just including that for completeness.

Now when I try to run Remote Backup the log shows it will create a full backup but then creates null.tar or null.zip, depending on whether or not I have a zip password set.  No backup file is ever created and thus never uploaded.

Please note that I've intentionally obscured the server name but it is accurate in the config and log.

Config:
custom_prefix: Automated_backup
debug: false
exclude_addons: ""
exclude_folders: ""
friendly_name: true
keep_local_backup: "3"
rclone_copy: false
rclone_enabled: false
rclone_remote: ""
rclone_remote_directory: ""
rclone_restore: false
rclone_sync: false
remote_directory: /mnt/main_data_pool/main_data_dataset/backups/HASSOS
rsync_enabled: false
rsync_exclude: ""
rsync_host: ""
rsync_password: ""
rsync_rootfolder: hassio-sync
rsync_user: ""
rsync_verbose: false
ssh_enabled: true
ssh_host: ***.***.com
ssh_host_key_algorithms: ""
ssh_key: id_rsa
ssh_port: "22"
ssh_user: terri
zip_password: ""

Log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Remote Backup
 Automatically create and backup HA backups using SCP
-----------------------------------------------------------
 Add-on version: 2022.7.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.4  (amd64 / qemux86-64)
 Home Assistant Core: 2022.8.0
 Home Assistant Supervisor: 2022.08.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[info] Adding SSH key
[info] SSH key added
[warn] Creating local backup: "Automated_backup 2022-08-11 21-33"
[info] Creating full backup
[info] Backup created: null
[warn] Copying null.tar to /mnt/main_data_pool/main_data_dataset/backups/HASSOS on ***.***.com using SCP
Warning: Permanently added '***.***.com' (ED25519) to the list of known hosts.
scp: stat local "null.tar": No such file or directory
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

I have also tried shortening the custom prefix to just "hass".  Didn't help.
HASSOS is running on a robust TrueNAS server in a Ubuntu VM.

**Comment by patman15** [comment]
Did you check that you have enough disk space? Try to create a backup via the GUI and see if that works. It looks to me like an issue with the backup creation by HA not like an issue of this addon.

**Comment by terri1769** [comment]
Yes.  I just double checked and ran a full backup via the gui.  It worked fine and completed as expected.

**Comment by patman15** [comment]
Ok then this issue can be closed. I will work on better error handling / reporting to make this more obvious. Thanks for the report!
