### ISSUE TITLE
Inconsistant naming of remote root folders

### ISSUE THREAD

**Issue by SirGoodenough** [ikifar2012/remote-backup-addon#71]
When the new version came out, this confused me, even though I've used the program years.
Adding something in the ssh remote directory line indicating it needs to be the root folder, like the one is set for rsync, would help clarify what is being asked for here.

![Screenshot_20220915_112846](https://user-images.githubusercontent.com/47349533/190458428-91b088df-8bb5-46c7-a4b2-deeb4ccb95f4.png)

I thought originally it wanted the path to SSL on the remote host or something.  Figured it out eventually.

**Comment by patman15** [comment]
We'll, since I wrote the description (text below the line) it's still logic to me. Can you please suggest a better text so I understand your issue?
