### ISSUE TITLE
Specify known_hosts and id

### ISSUE THREAD

**Issue by NicLogix** [ikifar2012/remote-backup-addon#76]
I have a custom folder keeping my known_hosts and id file, to persist between updates or reloads.
Is there a possibility change the addon to specify the location of these.
I connect to a couple of hosts passwordless by ssh-copy-id, pulling all kinds of stats.
I want to backup my snapshots/backup folder to one of these hosts.

**Comment by patman15** [comment]
The path is `/ssl` is hard coded in the source. You could of course change it there. In general it depends on where your folder is located. You could also try specifying the filename relative to the `/ssl` path in the configuration of the add-on.

**Comment by SirGoodenough** [comment]
> You could also try specifying the filename relative to the `/ssl` path in the configuration of the add-on.

That's cheating,,,   I had never thought of doing that...

**Comment by NicLogix** [comment]
Unfortunately my folder is at same height as the /ssl.
I will fork and see if I can figure this out.
Request closed, Thank you.

**Comment by SirGoodenough** [comment]
./ssl/../sameLevelelFolder/go down from there...
