### ISSUE TITLE
It is not possible to set backup_keep_local to 'null'

### ISSUE THREAD

**Issue by neillbell** [ikifar2012/remote-backup-addon#81]
The documentation says:
`To keep no local backups set this to null then all backups created will be removed after remote transfer.`
It is not possible to set this value to null since that value does not match the regexp for this option. Setting it to blank results in the complaint that the option is missing.

**Comment by patman15** [comment]
Hmm, you are right, this needs a fix.
Try switching to YAML mode and set `backup_keep_local: ""` that should work.

**Comment by neillbell** [comment]
That works. Thanks!
I can't believe I didn't try that.

**Comment by ikifar2012** [comment]
Give this a try with version 2022.12.0

**Comment by neillbell** [comment]
It looks like the copy to the remote destination is successful, but the backup remains on HA. Also, the log shows a warning:

[08:02:03] INFO: Creating non-encrypted full backup: "ha-backup- 2022-12-30 08-02"
[08:03:33] INFO: Backup created: 2c240b91
[08:03:33] INFO: Copying backup using SFTP/SCP.
scp: dest open ""/storage/homeassistant/ha-backup- 2022-12-30 08-02.tar"": No such file or directory

scp: failed to upload file /backup/2c240b91.tar to "/storage/homeassistant/ha-backup- 2022-12-30 08-02.tar"

[08:03:34] WARNING: SFTP transfer failed, falling back to SCP: Invalid command line argument
[08:03:36] INFO: Copying backup using rsync.
[08:03:50] INFO: Backup process done!

**Comment by patman15** [comment]
Can you please `enable debugging` and post the full log to see why the backup is not deleted?
The warning is "ok", it seems your remote machine does not support SFTP but only SCP.

**Comment by patman15** [comment]
> Give this a try with version 2022.12.0

@ikifar2012 https://github.com/ikifar2012/remote-backup-addon/pull/83 is not the correct fix I fear. You made "null" to keep all backups so it is now identical to "all". Nevertheless, the documentation says `set this to null then all backups created will be removed after remote transfer. ` I'll see if I can fix it if you are not faster than me. :)

**Comment by ikifar2012** [comment]
> > Give this a try with version 2022.12.0
> 
> @ikifar2012 #83 is not the correct fix I fear. You made "null" to keep all backups so it is now identical to "all". Nevertheless, the documentation says `set this to null then all backups created will be removed after remote transfer. ` I'll see if I can fix it if you are not faster than me. :)

My mistake, I will get to fixing it

**Comment by patman15** [comment]
I suggest to change the schema to
`  backup_keep_local: match(^(all|\d+)$)`
and the description (+ documentatio) to
`description: default is 'all', give a number for the last x backups to keep or set to 0 (zero) to immediately remove created backups after copying.`
Unfortunately, my code is not yet correct.

**Comment by ikifar2012** [comment]
> I suggest to change the schema to ` backup_keep_local: match(^(all|\d+)$)` and the description (+ documentatio) to `description: default is 'all', give a number for the last x backups to keep or set to 0 (zero) to immediately remove created backups after copying.` Unfortunately, my code is not yet correct.

we could also do that, I am open to feedback

**Comment by patman15** [comment]
As said, I would go for using 0. It is much more user friendly. Why would I be able to set 1, 2, 3, ... but not 0 and therefore have to use `null`? For me "keep local backups: 0" is much more intuitiv.

**Comment by ikifar2012** [comment]
> As said, I would go for using 0. It is much more user friendly. Why would I be able to set 1, 2, 3, ... but not 0 and therefore have to use `null`? For me "keep local backups: 0" is much more intuitiv.

I agree but I would like to avoid breaking existing configs, maybe we can do both
