### ISSUE TITLE
Known_hosts Question

### ISSUE THREAD

**Issue by SirGoodenough** [ikifar2012/remote-backup-addon#82]
Any idea how to clear this warning.  I've always seen it but it still works.
I thought sending it all to a new server might fix it, it doesn't. I had a server fail so had to reset everything.
I think that it is looking for this file on the HA host maybe.  Does this on both of my HA systems.
Nothing broke, but annoying.

```text
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[06:18:19] INFO: Adding SSH configuration.
[06:18:19] WARNING: Missing known_hosts file! Retrieving public key of remote host 10.10.100.10.
# 10.10.100.10:22 SSH-2.0-OpenSSH_8.4p1 Debian-5+deb11u1
[06:18:20] INFO: Creating local backup with password.
[06:18:20] INFO: Creating partial backup: "ChaloupkaAbode_backup 2022-12-11 06-18"
[06:18:20] NOTICE: Excluded folder(s):
media
```

**Comment by patman15** [comment]
Please see the tab "Documentation", you need to create a `known_hosts` file.

**Comment by patman15** [comment]
Did you take a look here?
![Bildschirmfoto vom 2022-12-12 19-19-53](https://user-images.githubusercontent.com/14628713/207123834-8b3a3adc-32ee-4f83-810f-0a4948f39900.png)

Yes, you are right, it should be referenced in the documentation as well. Will try to fix that.

**Comment by SirGoodenough** [comment]
When you said documentation, I looked there, not in the addon top blurb.  Missed that one completely.

**Comment by patman15** [comment]
Hmm, I just saw that I had already an [PR #42](https://github.com/ikifar2012/addons.mathesonsteplock.ca/pull/42) which was merged and the file is [there](https://github.com/ikifar2012/addons.mathesonsteplock.ca/blob/main/docs/addons/remote-backup/security.md). For some reason it does not show up in the [documentation](https://addons.mathesonsteplock.ca/docs/installation). @ikifar2012  can you fix that? Did I miss something?

**Comment by SirGoodenough** [comment]
42 is supposed to be the answer to everything somehow...

**Comment by ikifar2012** [comment]
@SirGoodenough I just fixed the issue, the documentation page was not linked in the sidebar 🤦‍♂️... It should be fixed now, let me know if that appears for you now
