### ISSUE TITLE
Synology SFTP Issue

### ISSUE THREAD

**Issue by ikifar2012** [ikifar2012/remote-backup-addon#88]
I tried to fix the double quote issue it worked in my test environment (even with a folder with spaces), with just a single set of quotes but now that I have pushed the update I am getting issues on my main box 
```bash
[21:21:35] INFO: Copying backup using SFTP/SCP.
scp: dest open "/volume1/backup/home-assistant/backup/Automated backup 2023-01-06 21-20.tar": No such file or directory
scp: failed to upload file /backup/29489512.tar to /volume1/backup/home-assistant/backup/Automated backup 2023-01-06 21-20.tar
[21:21:36] WARNING: SFTP transfer failed, falling back to SCP: Invalid command line argument
scp: ambiguous target
[21:21:36] ERROR: Error copying backup 29489512.tar to /volume1/backup/home-assistant/backup on 192.168.0.9:  Invalid command line argument
```

**Comment by patman15** [comment]
Hi @ikifar2012, with the original issue of the double quotes not working anymore I suspected that the change of the base image caused the issue. Unfortunately, I couldn't reproduce it by stepping back, no idea why. 
Now that you had to remove the `-s` option from the `scp` with another update of the base image, I'm pretty sure. The non-working option clearly hints that the `scp` binary was updated and changed it's behavior. Probably that helps a bit in searching the issue, I currently have not much time to contribute more.

**Comment by boardlord1** [comment]
> I tried to fix the double quote issue it worked in my test environment (even with a folder with spaces), with just a single set of quotes but now that I have pushed the update I am getting issues on my main box
> 
> ```shell
> [21:21:35] INFO: Copying backup using SFTP/SCP.
> scp: dest open "/volume1/backup/home-assistant/backup/Automated backup 2023-01-06 21-20.tar": No such file or directory
> scp: failed to upload file /backup/29489512.tar to /volume1/backup/home-assistant/backup/Automated backup 2023-01-06 21-20.tar
> [21:21:36] WARNING: SFTP transfer failed, falling back to SCP: Invalid command line argument
> scp: ambiguous target
> [21:21:36] ERROR: Error copying backup 29489512.tar to /volume1/backup/home-assistant/backup on 192.168.0.9:  Invalid command line argument
> ```

Hi, I've just encountered this, exact same error message. From your path I assume your target device is a Synology NAS, just like mine. After a fair amount of head scratching, I typed in an ls command through ssh (from hassio to Synology) and I got the list of usual directories. So... I manually tried to scp my backup file to Synology, and i OMITTED "volume1" from the remote path - et voilá it worked :)

**Comment by ikifar2012** [comment]
Interestingly, that seems to have worked for me changing "/volume1/backup/home-assistant/backup" to "/backup/home-assistant/backup" I guess synology changed something but when looking at the full path from my synology it includes volume1 and the path /backup does not exist, either way it works.

**Comment by boardlord1** [comment]
> Interestingly, that seems to have worked for me changing "/volume1/backup/home-assistant/backup" to "/backup/home-assistant/backup" I guess synology changed something but when looking at the full path from my synology it includes volume1 and the path /backup does not exist, either way it works.

It's not Synology, something changed in Home Assistant. If I scp something to my NAS from a shell on my router, I DO need to include "volume1" in the remote path. This is is only happening with Home Assistant.
